type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
  bio: String
}

type Restaurant @table {
  name: String!
  address: String!
  cuisine: String!
  createdAt: Timestamp!
  description: String
  phone: String
  website: String
  hoursOfOperation: String
  averageRating: Float
}

type MenuItem @table {
  restaurant: Restaurant!
  name: String!
  price: Float!
  createdAt: Timestamp!
  description: String
  category: String
}

type Review @table {
  user: User!
  restaurant: Restaurant!
  rating: Int!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  comment: String
  foodRating: Int
  serviceRating: Int
  ambianceRating: Int
}

type RestaurantList @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  isPublic: Boolean
}

type RestaurantListItem @table(key: ["restaurantList", "restaurant"]) {
  restaurantList: RestaurantList!
  restaurant: Restaurant!
  position: Int!
  note: String
}